kind: pipeline
name: default

steps:

  - name: build test image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t {{ cookiecutter.project_name}}-tests:${DRONE_COMMIT} -f Dockerfile.tests .

  - name: set permissions
    image: alpine:edge
    commands:
      - chown -Rv 1000:1000 .

  - name: py{{ cookiecutter.python_version|replace(".", "") }}
    image: {{ cookiecutter.project_name}}-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e py{{ cookiecutter.python_version|replace(".", "") }}

  - name: flake8
    image: {{ cookiecutter.project_name}}-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e flake8

  - name: pylint
    image: {{ cookiecutter.project_name}}-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e pylint

  - name: black
    image: {{ cookiecutter.project_name}}-tests:${DRONE_COMMIT}
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - tox -e black-only-check

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
