---
kind: pipeline
name: default

steps:

  - name: set permissions
    image: alpine:edge
    commands:
      - chown -Rv 1000:1000 .

  - name: py{{ ".".join(cookiecutter.python_version.split(".")[:2])|replace(".", "") }}
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e py{{ ".".join(cookiecutter.python_version.split(".")[:2])|replace(".", "") }}

  - name: bandit
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e bandit

  - name: prospector
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e prospector

  - name: mypy
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e mypy

  - name: black
    image: xsteadfastx/tox-python:minimal
    pull: true
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -v -e black-only-check

  - name: docs
    image: xsteadfastx/tox-python:minimal
    pull: true
    commands:
      - sudo apk add --no-cache gcc make musl-dev
      - make docs
