sudo: required
language: python
services:
  - docker
env:
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=mypy
before_install:
  - docker build --no-cache -t {{ cookiecutter.project_name }}-tests -f Dockerfile.tests .
script:
  - sudo chown -Rv 1000:1000 $PWD
  - docker run --rm -t -v $PWD:/data -w /data {{ cookiecutter.project_name }}-tests tox -v -e $TOXENV
