---
kind: pipeline
name: default

steps:

  - name: py37
    image: xsteadfastx/tox-python:minimal
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -e py37

  - name: flake8
    image: xsteadfastx/tox-python:minimal
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -e flake8

  - name: pylint
    image: xsteadfastx/tox-python:minimal
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -e pylint

  - name: black
    image: xsteadfastx/tox-python:minimal
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache gcc musl-dev
      - tox -e black-only-check

  - name: cookiecutter
    image: xsteadfastx/tox-python:minimal
    environment:
      TOX_WORK_DIR: /tmp/tox
    commands:
      - sudo apk add --no-cache git gcc make musl-dev
      - tox -e cookiecutter
