sudo: required
language: python
services:
  - docker
env:
  - TOXENV=py37
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=cookiecutter
before_install:
  - docker build -t cookiecutter-python-tests -f Dockerfile.tests .
script:
  - sudo chown -R 1000:1000 .
  - docker run --rm -t -v $PWD:/data -w /data -e TOX_WORK_DIR=/tmp cookiecutter-python-tests tox -v -e $TOXENV
