sudo: required
language: python
services:
  - docker
env:
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=cookiecutter
before_install:
  - docker build --no-cache -t tox-python -f Dockerfile.tests .
script:
  - sudo chown -Rv 1000:1000 $PWD
  - docker run --rm -t -v $PWD:/data -w /data tox-python tox -v -e $TOXENV
